<Project Sdk="Microsoft.NET.Sdk">

	<ItemGroup>
		<PackageReference Include="Asp.Versioning.Http" Version="10.0.1" />
		<PackageReference Include="DynamicExpression" Version="10.0.4" />
		<PackageReference Include="System.IdentityModel.Tokens.Jwt" Version="8.22.0" />
	</ItemGroup>

	<ItemGroup>
	  <ProjectReference Include="..\Nano.Common\Nano.Common.csproj" />
	</ItemGroup>
</Project>
