using System;
using System.Collections.Generic;
using System.Threading;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Authentication;
using Nano.Data.Abstractions.Exceptions;
using Nano.Data.Abstractions.Identity.Authentication.Models;

namespace Nano.Data.Abstractions.Identity.Authentication;

/// <inheritdoc />
public interface IIdentityAuthRepository : IIdentityAuthRepository<Guid>;

/// <summary>
/// Defines a repository for managing authentication for identity users of type <typeparamref name="TIdentity"/>.
/// </summary>
/// <typeparam name="TIdentity">The type used for the identity user key, which must implement <see cref="IEquatable{T}"/>.</typeparam>
/// <remarks>
///     Implementations of this interface handle:
///     <list type="bullet">
///         <item>User login with username/password, including generation of JWT access tokens.</item>
///         <item>External login using direct external login data or provider-specific login requests.</item>
///         <item>Refreshing access tokens using refresh tokens while validating the original JWT.</item>
///         <item>Logging out users and managing authentication state.</item>
///         <item>Retrieving the list of configured external authentication providers.</item>
///     </list>
///     Access tokens generated by this repository include user claims, roles, and optional external authentication tokens.
/// </remarks>
public interface IIdentityAuthRepository<TIdentity>
    where TIdentity : IEquatable<TIdentity>
{
    /// <summary>
    /// Retrieves the configured external login providers for the application.
    /// </summary>
    /// <param name="cancellationToken">A <see cref="CancellationToken"/> to cancel the operation.</param>
    /// <returns>A task that returns a collection of <see cref="AuthenticationScheme"/> representing available external login providers.</returns>
    Task<IEnumerable<AuthenticationScheme>> GetExternalProviderSchemesAsync(CancellationToken cancellationToken = default);

    /// <summary>
    /// Logs in a user using username and password credentials, generating a JWT access token and optional refresh token.
    /// </summary>
    /// <param name="logIn">The login request containing username, password, roles, claims, and refresh options.</param>
    /// <param name="cancellationToken">A <see cref="CancellationToken"/> to cancel the operation.</param>
    /// <returns>A task that returns an <see cref="AccessToken"/> for the authenticated user.</returns>
    /// <exception cref="UnauthorizedException">Thrown if the username/password are invalid.</exception>
    Task<AccessToken> LogInAsync(LogIn logIn, CancellationToken cancellationToken = default);

    /// <summary>
    /// Logs in a user using direct external login data, generating a JWT access token and optional refresh token.
    /// </summary>
    /// <param name="logInExternalDirect">The external login information, including provider data, roles, claims, and refresh options.</param>
    /// <param name="cancellationToken">A <see cref="CancellationToken"/> to cancel the operation.</param>
    /// <returns>A task that returns an <see cref="AccessToken"/> for the authenticated external user.</returns>
    Task<AccessToken> LogInExternalAsync(LogInExternalDirect logInExternalDirect, CancellationToken cancellationToken = default);

    /// <summary>
    /// Logs in a user using a generic external login provider, generating a JWT access token and optional refresh token.
    /// </summary>
    /// <typeparam name="TProvider">The external login provider type, derived from <see cref="BaseLogInExternalProvider"/>.</typeparam>
    /// <param name="logInExternalTransient">The external login request containing provider-specific data, roles, claims, and refresh options.</param>
    /// <param name="cancellationToken">A <see cref="CancellationToken"/> to cancel the operation.</param>
    /// <returns>A task that returns an <see cref="AccessToken"/> for the authenticated external user.</returns>
    /// <exception cref="UnauthorizedException">Thrown if the external login fails or no user is returned.</exception>
    Task<AccessToken> LogInExternalAsync<TProvider>(BaseLogInExternal<TProvider> logInExternalTransient, CancellationToken cancellationToken = default)
        where TProvider : BaseLogInExternalProvider, new();

    /// <summary>
    /// Refreshes an existing access token using a valid refresh token, generating a new JWT and refresh token.
    /// </summary>
    /// <param name="logInRefresh">The refresh login request containing the original token, refresh token, roles, and claims.</param>
    /// <param name="cancellationToken">A <see cref="CancellationToken"/> to cancel the operation.</param>
    /// <returns>A task that returns a new <see cref="AccessToken"/> with updated expiration.</returns>
    /// <exception cref="UnauthorizedException">
    /// Thrown if the refresh token is missing, invalid, expired, or does not match the stored token.
    /// </exception>
    Task<AccessToken> LogInRefreshAsync(LogInRefresh logInRefresh, CancellationToken cancellationToken = default);

    /// <summary>
    /// Logs out the current user, removing any server-side authentication state.
    /// </summary>
    /// <param name="cancellationToken">A <see cref="CancellationToken"/> to cancel the operation.</param>
    /// <returns>A task representing the asynchronous logout operation.</returns>
    Task LogOutAsync(CancellationToken cancellationToken = default);
}