version: 8.0.0.{build}
skip_tags: true
max_jobs: 1
image: Visual Studio 2022
configuration: Release
platform: Any CPU
force_https_clone: true
nuget:
  account_feed: false
  project_feed: false
environment:
  NUGET_HOST: https://www.nuget.org
  NUGET_APIKEY: 
    secure: GmL+s4FAMc4kMD/O+LST8XV2QXxjvpjV0muni1WttUxjwaQRXDwyXDRHpE3RvEl5
build: off
build_script:
- ps: >-
    dotnet build .\Nano.Library.sln;

    nuget update -self;
    nuget pack .\NanoCore.nuspec -symbols -SymbolPackageFormat snupkg;
test: off
artifacts:
- path: '**\*.nupkg'
  name: NuGet Package
- path: '**\*.snupkg'
  name: NuGet Symbol Package
deploy:
- provider: NuGet
  server: $(NUGET_HOST)
  api_key: $(NUGET_APIKEY)
  on:
    branch: master
