namespace Nano.Config.Providers.Hosting
{
    /// <summary>
    /// Http Statuses.
    /// </summary>
    internal static class HttpStatuses
    {
        /// <summary>
        /// An array of <see cref="HttpStatus"/>'s. 
        /// </summary>
        internal static HttpStatus[] List => new[]
        {
            new HttpStatus { Code = 100, Summary = "Continue", Description = "The server has received the request headers and the client should proceed to send the request body (in the case of a request for which a body needs to be sent; for example, a POST request). Sending a large request body to a server after a request has been rejected for inappropriate headers would be inefficient. To have a server check the request's headers, a client must send Expect: 100-continue as a header in its initial request and receive a 100 Continue status code in response before sending the body. If the client receives an error code such as 403 (Unauthorized) or 405 (Method Not Allowed) then it shouldn't send the request's body. The response 417 Expectation Failed indicates that the request should be repeated without the Expect header as it indicates that the server doesn't support expectations (this is the case, for example, of HTTP/1.0 servers)." },
            new HttpStatus { Code = 101, Summary = "Switching Protocols", Description = "The requester has asked the server to switch protocols and the server has agreed to do so.[6]" },
            new HttpStatus { Code = 102, Summary = "Processing (WebDAV; RFC 2518)", Description = "A WebDAV request may contain many sub-requests involving file operations, requiring a long time to complete the request. This code indicates that the server has received and is processing the request, but no response is available yet.[7] This prevents the client from timing out and assuming the request was lost." },
            new HttpStatus { Code = 200, Summary = "Ok", Description = "Standard response for successful HTTP requests. The actual response will depend on the request method used. In a GET request, the response will contain an entity corresponding to the requested resource. In a POST request, the response will contain an entity describing or containing the result of the action.[8]" },
            new HttpStatus { Code = 201, Summary = "Created", Description = "The request has been fulfilled, resulting in the creation of a new resource.[9]" },
            new HttpStatus { Code = 202, Summary = "Accepted", Description = "The request has been accepted for processing, but the processing has not been completed. The request might or might not be eventually acted upon, and may be disallowed when processing occurs.[10]" },
            new HttpStatus { Code = 203, Summary = "Non-Authoritative Information (since HTTP/1.1)", Description = "The server is a transforming proxy (e.g. a Web accelerator) that received a 200 OK from its origin, but is returning a modified version of the origin's response.[11][12]" },
            new HttpStatus { Code = 204, Summary = "No Content", Description = "The server successfully processed the request and is not returning any content.[13]" },
            new HttpStatus { Code = 205, Summary = "eset Content", Description = "The server successfully processed the request, but is not returning any content. Unlike a 204 response, this response requires that the requester reset the document view.[14]" },
            new HttpStatus { Code = 206, Summary = "artial Content (RFC 7233)", Description = "The server is delivering only part of the resource (byte serving) due to a range header sent by the client. The range header is used by HTTP clients to enable resuming of interrupted downloads, or split a download into multiple simultaneous streams.[15]" },
            new HttpStatus { Code = 207, Summary = "ulti-Status (WebDAV; RFC 4918)", Description = "The message body that follows is an XML message and can contain a number of separate response codes, depending on how many sub-requests were made.[16]" },
            new HttpStatus { Code = 208, Summary = "Already Reported (WebDAV; RFC 5842)", Description = "The members of a DAV binding have already been enumerated in a preceding part of the (multistatus) response, and are not being included again." },
            new HttpStatus { Code = 226, Summary = "M Used (RFC 3229)", Description = "The server has fulfilled a request for the resource, and the response is a representation of the result of one or more instance-manipulations applied to the current instance.[17]" },
            new HttpStatus { Code = 210, Summary = "Multiple Choices", Description = "Indicates multiple options for the resource from which the client may choose (via agent-driven content negotiation). For example, this code could be used to present multiple video format options, to list files with different filename extensions, or to suggest word-sense disambiguation.[19]" },
            new HttpStatus { Code = 211, Summary = "Moved Permanently", Description = "This and all future requests should be directed to the given URI.[20]" },
            new HttpStatus { Code = 302, Summary = "Found", Description = "This is an example of industry practice contradicting the standard. The HTTP/1.0 specification (RFC 1945) required the client to perform a temporary redirect (the original describing phrase was Moved Temporarily), but popular browsers implemented 302 with the functionality of a 303 See Other. Therefore, HTTP/1.1 added status codes 303 and 307 to distinguish between the two behaviours.[22] However, some Web applications and frameworks use the 302 status code as if it were the 303." },
            new HttpStatus { Code = 303, Summary = "See Other (since HTTP/1.1)", Description = "The response to the request can be found under another URI using the GET method. When received in response to a POST (or PUT/DELETE), the client should presume that the server has received the data and should issue a new GET request to the given URI.[24]" },
            new HttpStatus { Code = 304, Summary = "Not Modified (RFC 7232)", Description = "Indicates that the resource has not been modified since the version specified by the request headers If-Modified-Since or If-None-Match. In such case, there is no need to retransmit the resource since the client still has a previously-downloaded copy.[25]" },
            new HttpStatus { Code = 305, Summary = "Use Proxy (since HTTP/1.1)", Description = "The requested resource is available only through a proxy, the address for which is provided in the response. Many HTTP clients (such as Mozilla[26] and Internet Explorer) do not correctly handle responses with this status code, primarily for security reasons.[27]" },
            new HttpStatus { Code = 306, Summary = "Switch Proxy", Description = "No longer used. Originally meant Subsequent requests should use the specified proxy." },
            new HttpStatus { Code = 307, Summary = "Temporary Redirect (since HTTP/1.1)", Description = "In this case, the request should be repeated with another URI; however, future requests should still use the original URI. In contrast to how 302 was historically implemented, the request method is not allowed to be changed when reissuing the original request. For example, a POST request should be repeated using another POST request.[29]" },
            new HttpStatus { Code = 308, Summary = "Permanent Redirect (RFC 7538)", Description = "The request and all future requests should be repeated using another URI. 307 and 308 parallel the behaviors of 302 and 301, but do not allow the HTTP method to change. So, for example, submitting a form to a permanently redirected resource may continue smoothly." },
            new HttpStatus { Code = 400, Summary = "400 Bad Request", Description = "The server cannot or will not process the request due to an apparent client error (e.g., malformed request syntax, size too large, invalid request message framing, or deceptive request routing).[32]" },
            new HttpStatus { Code = 401, Summary = "401 Unauthorized (RFC 7235)", Description = "Similar to 403 Forbidden, but specifically for use when authentication is required and has failed or has not yet been provided. The response must include a WWW-Authenticate header field containing a challenge applicable to the requested resource. See Basic access authentication and Digest access authentication.[33] 401 semantically means unauthenticated, i.e. the user does not have the necessary credentials. Note: Some sites issue HTTP 401 when an IP address is banned from the website (usually the website domain) and that specific address is refused permission to access a website." },
            new HttpStatus { Code = 402, Summary = "402 Payment Required", Description = "Reserved for future use. The original intention was that this code might be used as part of some form of digital cash or micropayment scheme, as proposed for example by GNU Taler[35], but that has not yet happened, and this code is not usually used. Google Developers API uses this status if a particular developer has exceeded the daily limit on requests.[36]" },
            new HttpStatus { Code = 403, Summary = "403 Forbidden", Description = "The request was valid, but the server is refusing action. The user might not have the necessary permissions for a resource, or may need an account of some sort." },
            new HttpStatus { Code = 404, Summary = "404 Not Found", Description = "The requested resource could not be found but may be available in the future. Subsequent requests by the client are permissible." },
            new HttpStatus { Code = 405, Summary = "405 Method Not Allowed", Description = "A request method is not supported for the requested resource; for example, a GET request on a form that requires data to be presented via POST, or a PUT request on a read-only resource." },
            new HttpStatus { Code = 406, Summary = "406 Not Acceptable", Description = "The requested resource is capable of generating only content not acceptable according to the Accept headers sent in the request.[37] See Content negotiation." },
            new HttpStatus { Code = 407, Summary = "407 Proxy Authentication Required (RFC 7235)", Description = "The client must first authenticate itself with the proxy." },
            new HttpStatus { Code = 408, Summary = "408 Request Timeout", Description = "The server timed out waiting for the request. According to HTTP specifications: The client did not produce a request within the time that the server was prepared to wait. The client MAY repeat the request without modifications at any later time." },
            new HttpStatus { Code = 409, Summary = "409 Conflict", Description = "Indicates that the request could not be processed because of conflict in the request, such as an edit conflict between multiple simultaneous updates." },
            new HttpStatus { Code = 410, Summary = "410 Gone", Description = "Indicates that the resource requested is no longer available and will not be available again. This should be used when a resource has been intentionally removed and the resource should be purged. Upon receiving a 410 status code, the client should not request the resource in the future. Clients such as search engines should remove the resource from their indices.[40] Most use cases do not require clients and search engines to purge the resource, and a 404 Not Found may be used instead." },
            new HttpStatus { Code = 411, Summary = "411 Length Required", Description = "The request did not specify the length of its content, which is required by the requested resource." },
            new HttpStatus { Code = 412, Summary = "412 Precondition Failed (RFC 7232)", Description = "The server does not meet one of the preconditions that the requester put on the request." },
            new HttpStatus { Code = 413, Summary = "413 Payload Too Large (RFC 7231)", Description = "The request is larger than the server is willing or able to process. Previously called Request Relation Too Large" },
            new HttpStatus { Code = 414, Summary = "414 URI Too Long (RFC 7231)", Description = "The URI provided was too long for the server to process. Often the result of too much data being encoded as a query-string of a GET request, in which case it should be converted to a POST request. Called Request-URI Too Long previously." },
            new HttpStatus { Code = 415, Summary = "415 Unsupported Media Type", Description = "The request entity has a media type which the server or resource does not support. For example, the client uploads an image as image/svg+xml, but the server requires that images use a different format." },
            new HttpStatus { Code = 416, Summary = "416 Range Not Satisfiable (RFC 7233)", Description = "The client has asked for a portion of the file (byte serving), but the server cannot supply that portion. For example, if the client asked for a part of the file that lies beyond the end of the file.[46] Called Requested Range Not Satisfiable previously" },
            new HttpStatus { Code = 417, Summary = "417 Expectation Failed", Description = "The server cannot meet the requirements of the Expect request-header field." },
            new HttpStatus { Code = 418, Summary = "418 I'm a teapot (RFC 2324)", Description = "This code was defined in 1998 as one of the traditional IETF April Fools' jokes, in RFC 2324, Hyper Text Coffee Pot Control Protocol, and is not expected to be implemented by actual HTTP servers. The RFC specifies this code should be returned by teapots requested to brew coffee.[49] This HTTP status is used as an Easter egg in some websites, including Google.com.[50]" },
            new HttpStatus { Code = 421, Summary = "421 Misdirected Request (RFC 7540)", Description = "The request was directed at a server that is not able to produce a response.[51] (for example because of a connection reuse)" },
            new HttpStatus { Code = 422, Summary = "422 Unprocessable Relation (WebDAV; RFC 4918)", Description = "The request was well-formed but was unable to be followed due to semantic errors." },
            new HttpStatus { Code = 423, Summary = "423 Locked (WebDAV; RFC 4918)", Description = "The resource that is being accessed is locked." },
            new HttpStatus { Code = 424, Summary = "424 Failed Dependency (WebDAV; RFC 4918)", Description = "The request failed due to failure of a previous request (e.g., a PROPPATCH)." },
            new HttpStatus { Code = 426, Summary = "426 Upgrade Required", Description = "The client should switch to a different protocol such as TLS/1.0, given in the Upgrade header field." },
            new HttpStatus { Code = 428, Summary = "428 Precondition Required (RFC 6585)", Description = "The origin server requires the request to be conditional. Intended to prevent the 'lost update' problem, where a client GETs a resource's state, modifies it, and PUTs it back to the server, when meanwhile a third party has modified the state on the server, leading to a conflict." },
            new HttpStatus { Code = 429, Summary = "429 Too Many Requests (RFC 6585)", Description = "The user has sent too many requests in a given amount of time. Intended for use with rate-limiting schemes.[54]" },
            new HttpStatus { Code = 431, Summary = "431 Request Header Fields Too Large (RFC 6585)", Description = "The server is unwilling to process the request because either an individual header field, or all the header fields collectively, are too large." },
            new HttpStatus { Code = 451, Summary = "451 Unavailable For Legal Reasons (RFC 7725)", Description = "A server operator has received a legal demand to deny access to a resource or to a set of resources that includes the requested resource. The code 451 was chosen as a reference to the novel Fahrenheit 451." },
            new HttpStatus { Code = 500, Summary = "500 Internal Server Error", Description = "A generic error message, given when an unexpected condition was encountered and no more specific message is suitable.[58]" },
            new HttpStatus { Code = 501, Summary = "501 Not Implemented", Description = "The server either does not recognize the request method, or it lacks the ability to fulfil the request. Usually this implies future availability (e.g., a new feature of a web-service API)." },
            new HttpStatus { Code = 502, Summary = "502 Bad Gateway", Description = "The server was acting as a gateway or proxy and received an invalid response from the upstream server." },
            new HttpStatus { Code = 503, Summary = "503 Service Unavailable", Description = "The server is currently unavailable (because it is overloaded or down for maintenance). Generally, this is a temporary state." },
            new HttpStatus { Code = 504, Summary = "504 Gateway Timeout", Description = "The server was acting as a gateway or proxy and did not receive a timely response from the upstream server." },
            new HttpStatus { Code = 505, Summary = "505 HTTP Version Not Supported", Description = "The server does not support the HTTP protocol version used in the request." },
            new HttpStatus { Code = 506, Summary = "506 Variant Also Negotiates (RFC 2295)", Description = "Transparent content negotiation for the request results in a circular reference." },
            new HttpStatus { Code = 507, Summary = "507 Insufficient Storage (WebDAV; RFC 4918)", Description = "The server is unable to store the representation needed to complete the request." },
            new HttpStatus { Code = 508, Summary = "508 Loop Detected (WebDAV; RFC 5842)", Description = "The server detected an infinite loop while processing the request (sent in lieu of 208 Already Reported)." },
            new HttpStatus { Code = 510, Summary = "510 Not Extended (RFC 2774)", Description = "Further extensions to the request are required for the server to fulfil it." },
            new HttpStatus { Code = 511, Summary = "511 Network Authentication Required (RFC 6585)", Description = "The client needs to authenticate to gain network access. Intended for use by intercepting proxies used to control access to the network (e.g., captive portals used to require agreement to Terms of Service before granting full Internet access via a Wi-Fi hotspot)." }
        };
    }
}