name: Build and Deploy
on:
  pull_request:
    branches:
      - master 
  push:
    branches:
      - master 
env:
  APP_NAME: Nano.Library
  VERSION: 10.0.0-preview1
  NUGET_HOST: https://api.nuget.org/v3/index.json
  NUGET_APIKEY: ${{ secrets.NUGET_APIKEY }}
  NUGET_HOST_PREVIEW: https://nuget.pkg.github.com/Nano-Core/index.json
  NUGET_APIKEY_PREVIEW: ${{ secrets.GITHUB_TOKEN }}
jobs:
  build-and-deploy:
    runs-on: windows-latest
    permissions:
      contents: write
      packages: write
      id-token: write
    concurrency:
      group: ${{ github.repository }}
      cancel-in-progress: false
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 10.0.x

      - name: Build, Test and Pack
        shell: pwsh
        run: |
          dotnet build -c Release .\$env:APP_NAME.sln;

          if ($LastExitCode -ne 0)
          { 
              throw "Build Failed";
          };

          dotnet test -c Release --no-build .\.tests\Tests.$env:APP_NAME\Tests.$env:APP_NAME.csproj;

          if ($LastExitCode -ne 0)
          { 
              throw "Tests Failed";
          };

          dotnet pack -c Release --no-build -o nupkgs /p:Version=$env:VERSION;

          if ($LastExitCode -ne 0)
          { 
              throw "NuGet Pack Failed";
          };

      - name: Push to NuGet.org
        if: github.ref == 'refs/heads/master'
        run: |
          dotnet nuget push "**/nupkgs/*.nupkg" `
              --source ${{ secrets.NUGET_HOST }} `
              --api-key ${{ secrets.NUGET_APIKEY }} `
              --skip-duplicate;

          if ($LastExitCode -ne 0)
          { 
              throw "Publish Failed";
          };

      - name: Push to GitHub Packages
        if: github.ref != 'refs/heads/master'
        run: |
          dotnet nuget push "**/nupkgs/*.nupkg" `
              --source ${{ secrets.NUGET_HOST_PREVIEW }} `
              --api-key ${{ secrets.NUGET_APIKEY_PREVIEW }} `
              --skip-duplicate;

          if ($LastExitCode -ne 0)
          { 
              throw "Publish Failed";
          };

      - name: GitHub Release
        if: github.ref == 'refs/heads/master'
        uses: ncipollo/release-action@v1
        with:
          tag: v${{ env.VERSION }}
          name: "Release ${{ env.VERSION }}"
          body: |
            Version: ${{ env.VERSION }}
            Commit: ${{ github.sha }}
          artifacts: "nupkgs/*"
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false